name: CI
on: [push]

env:
  OTP_VERSION: '23'
  ELIXIR_VERSION: '^1.11.2'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - name: Get Dependencies
        run: mix deps.get
      - name: Compile
        run: mix compile
      - name: Test
        run: mix test
