name: CI
on: [push]

env:
  OTP_VERSION: '23'
  ELIXIR_VERSION: '^1.11.2'

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - name: Cache Mix Dependencies
        uses: actions/cache@v2
        env:
          base-key: ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-build-mix-deps
        with:
          path: deps
          key: ${{ env.base-key }}-${{ hashFiles('**/mix.lock') }}
      - name: Get Dependencies
        run: mix deps.get
      - name: Compile
        run: mix compile
      - name: Test
        run: mix test
  dialyzer:
    name: Dialyzer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - name: Cache PLT
        uses: actions/cache@v2
        env:
          base-key: ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-build-plt
          plt-core-path: '_build/dev'
        with:
          path: |
            ${{ env.plt-core-path }}/dialyzer.plt
            ${{ env.plt-core-path }}/dialyzer.plt.hash
          key: ${{ env.base-key }}-${{ hashFiles('**/mix.lock') }}
      - name: Get Dependencies
        run: mix deps.get
      - name: Compile
        run: mix compile
      - name: Run Dialyzer
        run: mix dialyzer

